name: Haiku Build

on:
  workflow_dispatch:

jobs:
  build-haiku:
    runs-on: ubuntu-22.04
    env:
      HAUL_HOME: ${{ github.workspace }}/haiku-dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential gcc g++ make automake autoconf \
            texinfo flex bison gawk unzip zip nasm yasm pkg-config libtool \
            libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev

      - name: Run build script
        run: bash scripts/build_haiku.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: haiku-iso
          path: ${{ github.workspace }}/haiku-dev/haiku/generated.x86_64/obj/images

